import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/Header";
import { Footer } from "./_components/Footer";

import "@mantine/core/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Train Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <link href="/kettlebell.svg" rel="shortcut icon" />
        <link href="https://css.gg/css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <Header />
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
